version: 1.0.{build}
os: Visual Studio 2015
configuration: Debug
clone_depth: 1
before_build:
- echo %TIME%
- git submodule update --init
- echo %TIME%
- cmake .
- echo %TIME%
build:
  project: MCServer.sln
  parallel: true
  verbosity: minimal
